#application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync
  namespace: argocd
spec:
  project: default
  source:
     repoURL: https://github.com/Tykama/argocd-sync.git
     targetRevision: HEAD
     path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true